# Generated by Django 5.1.5 on 2025-01-28 09:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ['id'], 'verbose_name': 'Μέλος Οικογένειας', 'verbose_name_plural': 'Μέλη Οικογένειας'},
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='learner',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='order',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='folder_name',
        ),
        migrations.AddField(
            model_name='learner',
            name='gender',
            field=models.CharField(choices=[('male', 'Άνδρας'), ('female', 'Γυναίκα')], default='male', max_length=10, verbose_name='Φύλο'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='birth_date',
            field=models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Ημερομηνία γέννησης'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='education',
            field=models.CharField(max_length=200, verbose_name='Εκπαίδευση'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='health_status',
            field=models.TextField(verbose_name='Κατάσταση υγείας'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='occupation',
            field=models.CharField(max_length=200, verbose_name='Επάγγελμα'),
        ),
        migrations.CreateModel(
            name='SocialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=255, verbose_name='ΦΑΚΕΛΟΣ: ΟΝΟΜΑΤΕΠΩΝΥΜΟ')),
                ('rv_group', models.CharField(max_length=255, verbose_name='RV Διεπιστημονική Ομάδα')),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socialhistory', to='learners.learner', verbose_name='Ωφελούμενος')),
            ],
            options={
                'verbose_name': 'Κοινωνικό Ιστορικό',
                'verbose_name_plural': 'Κοινωνικά Ιστορικά',
            },
        ),
        migrations.AddField(
            model_name='familymember',
            name='social_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='learners.socialhistory', verbose_name='Κοινωνικό Ιστορικό'),
        ),
    ]
