# Generated by Django 5.1.5 on 2025-01-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0002_alter_familymember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialhistory',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Οποιεσδήποτε άλλες σημαντικές πληροφορίες', null=True, verbose_name='Πρόσθετες Σημειώσεις'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='benefits',
            field=models.TextField(blank=True, help_text='Καταγράψτε τυχόν επιδόματα ή παροχές που λαμβάνει', null=True, verbose_name='Επιδόματα/Παροχές'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='family_issues',
            field=models.TextField(blank=True, help_text='Καταγράψτε τυχόν σημαντικά οικογενειακά προβλήματα', null=True, verbose_name='Οικογενειακά Προβλήματα'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='family_relations',
            field=models.TextField(blank=True, help_text='Περιγράψτε την ποιότητα των οικογενειακών σχέσεων', null=True, verbose_name='Οικογενειακές Σχέσεις'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='housing_details',
            field=models.TextField(blank=True, help_text='Περιγράψτε τις συνθήκες διαβίωσης', null=True, verbose_name='Λεπτομέρειες Κατοικίας'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('owned', 'Ιδιόκτητη'), ('rented', 'Ενοικιαζόμενη'), ('parents', 'Συγκατοίκηση με γονείς'), ('other', 'Άλλο')], max_length=20, null=True, verbose_name='Τύπος Κατοικίας'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='income_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Πηγή Εισοδήματος'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Άγαμος/η'), ('married', 'Έγγαμος/η'), ('divorced', 'Διαζευγμένος/η'), ('widowed', 'Χήρος/α'), ('separated', 'Σε διάσταση')], max_length=20, null=True, verbose_name='Οικογενειακή Κατάσταση'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Μηνιαίο Εισόδημα'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='support_network',
            field=models.TextField(blank=True, help_text='Περιγράψτε το υποστηρικτικό δίκτυο της οικογένειας', null=True, verbose_name='Υποστηρικτικό Δίκτυο'),
        ),
    ]
