# Generated by Django 5.1.5 on 2025-01-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0004_alter_learner_decision_announcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialhistory',
            name='guardian_emails',
            field=models.JSONField(blank=True, default=list, help_text='Προσθέστε ένα ή περισσότερα email', verbose_name='Email δικαστικού συμπαραστάτη'),
        ),
    ]
