# Generated by Django 5.1.5 on 2025-01-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0005_socialhistory_guardian_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialhistory',
            name='guardian_emails',
            field=models.JSONField(blank=True, default=list, help_text='Προσθέστε ένα ή περισσότερα email', null=True, verbose_name='Email δικαστικού συμπαραστάτη'),
        ),
    ]
