# Generated by Django 5.1.5 on 2025-01-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0006_alter_socialhistory_guardian_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='social_worker',
        ),
    ]
