# Generated by Django 5.1.5 on 2025-01-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0007_remove_learner_social_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialhistory',
            name='disability_percentage',
            field=models.CharField(blank=True, choices=[('67', '67%'), ('80', '80%'), ('other', 'Άλλο')], max_length=10, null=True, verbose_name='Προνοιακό επίδομα με ποσοστό αναπηρίας'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='other_disability_percentage',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Άλλο ποσοστό αναπηρίας'),
        ),
    ]
