# Generated by Django 5.1.5 on 2025-01-28 10:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0008_socialhistory_disability_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialhistory',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='disability_percentage',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='family_issues',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='family_relations',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='folder_name',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='guardian_emails',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='housing_details',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='housing_type',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='income_source',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='monthly_income',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='other_disability_percentage',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='rv_group',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='support_network',
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='arrival_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Ημερομηνία Προσέλευσης'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Σχόλια'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='interdisciplinary_team',
            field=models.CharField(blank=True, max_length=200, verbose_name='Διεπιστημονική Ομάδα'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='rv_team',
            field=models.CharField(blank=True, max_length=200, verbose_name='RV Διεπιστημονική Ομάδα'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='status',
            field=models.CharField(choices=[('active', 'Ενεργός'), ('inactive', 'Ανενεργός'), ('pending', 'Σε αναμονή')], default='active', max_length=20, verbose_name='Κατάσταση'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Τελευταία Ενημέρωση'),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='learner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_history', to='learners.learner', verbose_name='Ωφελούμενος'),
        ),
    ]
