# Generated by Django 5.1.5 on 2025-01-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0009_remove_socialhistory_additional_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='disability_percentage',
            field=models.CharField(choices=[('67', '67%'), ('80', '80%'), ('other', 'Άλλο')], default='67', max_length=10, verbose_name='Ποσοστό Αναπηρίας'),
        ),
        migrations.AddField(
            model_name='learner',
            name='other_disability_percentage',
            field=models.IntegerField(blank=True, help_text='Συμπληρώστε εάν επιλέξατε "Άλλο"', null=True, verbose_name='Άλλο ποσοστό αναπηρίας'),
        ),
    ]
