# Generated by Django 5.1.5 on 2025-01-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0011_learner_additional_guardian_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='guardian_marital_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Οικογενειακή Κατάσταση Δικαστικού Συμπαραστάτη'),
        ),
        migrations.AlterField(
            model_name='learner',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Οικογενειακή Κατάσταση'),
        ),
    ]
