# Generated by Django 5.1.5 on 2025-01-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0013_alter_familymember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='member1_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία γέννησης 1ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member1_education',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Εκπαίδευση 1ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member1_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Όνομα 1ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member1_health',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Κατάσταση υγείας 1ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member1_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Επώνυμο 1ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member1_occupation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Επάγγελμα 1ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member1_relation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Συγγενική σχέση 1ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member2_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία γέννησης 2ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member2_education',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Εκπαίδευση 2ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member2_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Όνομα 2ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member2_health',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Κατάσταση υγείας 2ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member2_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Επώνυμο 2ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member2_occupation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Επάγγελμα 2ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member2_relation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Συγγενική σχέση 2ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member3_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία γέννησης 3ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member3_education',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Εκπαίδευση 3ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member3_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Όνομα 3ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member3_health',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Κατάσταση υγείας 3ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member3_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Επώνυμο 3ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member3_occupation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Επάγγελμα 3ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member3_relation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Συγγενική σχέση 3ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member4_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία γέννησης 4ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member4_education',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Εκπαίδευση 4ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member4_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Όνομα 4ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member4_health',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Κατάσταση υγείας 4ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member4_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Επώνυμο 4ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member4_occupation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Επάγγελμα 4ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member4_relation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Συγγενική σχέση 4ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member5_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία γέννησης 5ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member5_education',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Εκπαίδευση 5ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member5_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Όνομα 5ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member5_health',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Κατάσταση υγείας 5ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member5_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Επώνυμο 5ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member5_occupation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Επάγγελμα 5ου μέλους'),
        ),
        migrations.AddField(
            model_name='learner',
            name='member5_relation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Συγγενική σχέση 5ου μέλους'),
        ),
    ]
