# Generated by Django 5.1.5 on 2025-01-28 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Όνομα')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
            ],
            options={
                'verbose_name': 'Δραστηριότητα',
                'verbose_name_plural': 'Δραστηριότητες',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Όνομα')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('activities', models.ManyToManyField(blank=True, related_name='classes', to='classes.activity', verbose_name='Δραστηριότητες')),
            ],
            options={
                'verbose_name': 'Τμήμα',
                'verbose_name_plural': 'Τμήματα',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Δευτέρα'), (1, 'Τρίτη'), (2, 'Τετάρτη'), (3, 'Πέμπτη'), (4, 'Παρασκευή')], verbose_name='Ημέρα')),
                ('time_slot', models.CharField(choices=[('08:00-09:00', '08:00-09:00'), ('09:00-10:00', '09:00-10:00'), ('10:00-11:00', '10:00-11:00'), ('11:00-12:00', '11:00-12:00'), ('12:00-13:00', '12:00-13:00'), ('13:00-14:00', '13:00-14:00'), ('14:00-15:00', '14:00-15:00'), ('15:00-16:00', '15:00-16:00'), ('16:00-17:00', '16:00-17:00'), ('17:00-18:00', '17:00-18:00')], max_length=20, verbose_name='Ώρα')),
                ('activity', models.CharField(blank=True, max_length=100, verbose_name='Δραστηριότητα')),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='classes.class')),
            ],
            options={
                'verbose_name': 'Πρόγραμμα',
                'verbose_name_plural': 'Προγράμματα',
                'ordering': ['weekday', 'time_slot'],
                'unique_together': {('class_instance', 'weekday', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Ημερομηνία Ανάθεσης')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='classes.class', verbose_name='Τμήμα')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Εκπαιδευτικός')),
            ],
            options={
                'verbose_name': 'Ανάθεση Εκπαιδευτικού',
                'verbose_name_plural': 'Αναθέσεις Εκπαιδευτικών',
                'unique_together': {('teacher', 'class_group')},
            },
        ),
    ]
